### ISSUE TITLE
medical_dialogue数据集问题

### ISSUE THREAD

**Issue by YJSoooooo** [FudanDISC/DISC-MedLLM#10]
大佬，您好！刚刚拜读了您的DISC-MedLLM这篇论文，您不仅介绍了数据集构建，还分享了处理后的数据集。我今天也拿到了medical_dialogue数据集，我想问一下您在处理这部分数据的时候，保留了哪些字段，丢弃了哪些字段。
![image](https://github.com/FudanDISC/DISC-MedLLM/assets/125850867/3a20faba-be9c-49cd-a75d-63eb82ccf02d)

我看到您的数据集，在第一轮对话中，只抽取了【疾病：，病情描述：， 】希望获得的帮助这个字段您保留了吗， 我看到剩下的几个字段包括【患病多久：，过敏史：】都没有保留

希望大佬可以回答我的问题，感谢！！！！

**Comment by YJSoooooo** [comment]
如果大佬可以提供一下medical_dialogue数据集的处理脚本那就太好了。我的邮箱：107552204107@stu.xju.edu.cn

**Comment by F1mc** [comment]
该数据集作者提供了经过预处理的版本
