### ISSUE TITLE
模型的配置和分词器

### ISSUE THREAD

**Issue by gms5144** [FudanDISC/DISC-MedLLM#11]
![image](https://github.com/FudanDISC/DISC-MedLLM/assets/91517592/e151ecca-fb34-405c-861c-c8e8316b63c2)
这段代码中的模型配置文件和分词器是必须用自己微调后的才行吗？可以直接调用你们训练好的模型吗

**Comment by F1mc** [comment]
分词器并不需要经过微调，使用预训练模型原版即可
