### ISSUE TITLE
算法评估里，第二轮对话用户的提问是怎么生成的？

### ISSUE THREAD

**Issue by auroua** [FudanDISC/DISC-MedLLM#5]
麻烦请教一下，在这个评估文件里`eval/dialogues/DISC-MedLLM_cmd.json`，第一轮对话的用户提问是从数据集里得到的，第二轮对话的用户提问是怎么生成的？

是你们自己写的么？我看不同的模型，第二轮开始的体问都不一样。

谢谢

**Comment by F1mc** [comment]
技术报告里有写道，由GPT3.5扮演患者与模型进行对话，起始问题固定

**Comment by auroua** [comment]
谢谢，明白了
